# Generated by Django 3.1.5 on 2021-01-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('genre1', models.CharField(blank=True, max_length=100, null=True)),
                ('laenge', models.CharField(max_length=100)),
                ('regie', models.CharField(max_length=100)),
                ('imdb_rating', models.CharField(max_length=100)),
                ('flim_lusting', models.CharField(max_length=100)),
                ('flim_trauring', models.CharField(max_length=100)),
                ('flim_spannend', models.CharField(max_length=100)),
                ('mood_rating', models.CharField(max_length=100)),
            ],
        ),
    ]
