# Generated by Django 3.1.5 on 2021-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='jahr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
