# Generated by Django 3.1.5 on 2021-01-19 13:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_movies_jahr'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Happy'), (2, 'Average'), (3, 'Sad')], max_length=30, null=True),
        ),
    ]
