# Generated by Django 3.1.5 on 2021-01-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210119_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='flim_lusting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='flim_spannend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='flim_trauring',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mood_rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
