# Generated by Django 3.1.5 on 2021-01-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_movies_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='flim_lusting',
            new_name='film_intense',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='flim_spannend',
            new_name='funny_film',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='flim_trauring',
            new_name='sad_film',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='mood_rating',
        ),
    ]
